#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
REPO_ROOT="${ARCANUM_REPO_ROOT:-$(cd "$SCRIPT_DIR/../.." && pwd)}"
CHAIN_DIR="${ARCANUM_CHAIN_DIR:-$REPO_ROOT/chains/arcanum}"
NODE_HOME="${ARCANUM_NODE_HOME:-$REPO_ROOT/.local/arcnet-node}"
BIN_DIR="${ARCANUM_BIN_DIR:-$REPO_ROOT/.local/bin}"
ARCANUMD="${ARCANUMD:-$BIN_DIR/arcanumd}"
CHAIN_ID="${ARCANUM_CHAIN_ID:-arcanum-local-1}"
MONIKER="${ARCANUM_MONIKER:-architect-local}"

case "$NODE_HOME" in
  "$REPO_ROOT"/.local/*) ;;
  *)
    echo "Refusing to reset node home outside repository .local directory: $NODE_HOME" >&2
    echo "Set ARCANUM_NODE_HOME under $REPO_ROOT/.local or reset manually." >&2
    exit 1
    ;;
esac

echo "== local ARCnet reset =="
echo "repo:       $REPO_ROOT"
echo "chain dir:  $CHAIN_DIR"
echo "node home:  $NODE_HOME"
echo "binary:     $ARCANUMD"
echo "chain id:   $CHAIN_ID"
echo "moniker:    $MONIKER"
echo

echo "[1/4] Removing local node home"
rm -rf "$NODE_HOME"
mkdir -p "$NODE_HOME" "$BIN_DIR"

echo "[2/4] Building arcanumd"
(
  cd "$CHAIN_DIR"
  go build -o "$ARCANUMD" ./cmd/arcanumd
)

echo "[3/4] Checking daemon version"
"$ARCANUMD" version || true

echo "[4/4] Initializing local node home when supported"
if "$ARCANUMD" init "$MONIKER" --chain-id "$CHAIN_ID" --home "$NODE_HOME" >/tmp/arcanum-local-init.log 2>&1; then
  cat /tmp/arcanum-local-init.log
  echo "Initialized local node home."
else
  cat /tmp/arcanum-local-init.log || true
  echo "Daemon init did not complete. This is acceptable while the node scaffold is still Pre-Genesis." >&2
  echo "The binary was built and the local home directory was prepared." >&2
fi
rm -f /tmp/arcanum-local-init.log

cat > "$NODE_HOME/README.local.md" <<EOF
# Local ARCnet Node Home

This directory is generated by scripts/node/local-reset.sh.

It is local developer state only.

It does not represent production chain state, validator authority, governance authority, MANA truth, or agent execution.
EOF

echo
echo "✅ local reset complete"
echo "Next: bash scripts/node/local-status.sh"