#!/usr/bin/env bash
# Regression proof for normal-merge repo-index promotion stability.

set -euo pipefail

ROOT_DIR="$(git rev-parse --show-toplevel)"
GENERATOR="$ROOT_DIR/scripts/repo-index.sh"
TMP_DIR="$(mktemp -d)"
trap 'rm -rf "$TMP_DIR"' EXIT

FIXTURE="$TMP_DIR/repo"
mkdir -p "$FIXTURE/scripts"
cp "$GENERATOR" "$FIXTURE/scripts/repo-index.sh"

cd "$FIXTURE"
git init -q -b main
git config user.name "repo-index-regression"
git config user.email "repo-index-regression@example.invalid"
git remote add origin https://github.com/example/repo.git

mkdir -p docs/repo
printf 'base\n' > base.txt
git add base.txt scripts/repo-index.sh
git commit -q -m "fixture: base"

git checkout -q -b work/fixture
printf 'source\n' > promoted.txt
git add promoted.txt
git commit -q -m "fixture: substantive source"
SOURCE_SHA="$(git rev-parse HEAD)"

bash scripts/repo-index.sh >/dev/null
python3 - <<'PY'
import json
from pathlib import Path

index = json.loads(Path("docs/repo/repo-index.json").read_text(encoding="utf-8"))
assert index["generator_version"] == "1.5", index["generator_version"]
PY

git add docs/repo/repo-index.json
git commit -q -m "fixture: generated index companion"
cp docs/repo/repo-index.json "$TMP_DIR/index-before-merge.json"
COMPANION_SHA="$(git rev-parse HEAD)"

git checkout -q main
git merge -q --no-ff --no-edit "$COMPANION_SHA"
MERGE_SHA="$(git rev-parse HEAD)"

test "$MERGE_SHA" != "$SOURCE_SHA"
test "$MERGE_SHA" != "$COMPANION_SHA"

bash scripts/repo-index.sh >/dev/null
cmp -s "$TMP_DIR/index-before-merge.json" docs/repo/repo-index.json

python3 - "$SOURCE_SHA" <<'PY'
import json
import sys
from pathlib import Path

source = sys.argv[1]
index = json.loads(Path("docs/repo/repo-index.json").read_text(encoding="utf-8"))
assert index["commit"] == source[:9], (index["commit"], source[:9])
PY

echo "PASS repo-index merge stability: normal merge preserved exact generated bytes for source ${SOURCE_SHA:0:9}"
