[package]
name = "arcanum-android-tempus-lifecycle-jni"
version = "0.1.0"
edition = "2021"
rust-version = "1.82"
publish = false

[lib]
name = "arcanum_android_tempus_lifecycle_jni"
path = "src/lib.rs"
crate-type = ["cdylib"]

[dependencies]
arcanum-android-tempus-lifecycle = { path = "../arcanum-android-tempus-lifecycle" }
jni = { version = "=0.21.1", default-features = false }
